name: CI/CD Deploy Frontend to VPS

on:
  release:
    types: [published]
  push:
    branches: ["main", "master"]
    paths-ignore:
      - "**.md"
      - "docs/**"
  workflow_dispatch: # เปิดให้กดรัน Manual ผ่าน GitHub ได้

jobs:
  redeploy:
    name: Build Docker image and Trigger Webhook Deploy
    runs-on: ubuntu-latest

    steps:
      # 1. แจ้งเตือนเริ่มการทำงานเข้า Discord
      - name: Discord notification (start)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: github_server
          DISCORD_AVATAR: https://picsum.photos/id/237/200/300
        uses: Ilshidur/action-discord@master
        with:
          args: "The project {{ EVENT_PAYLOAD.repository.full_name }} has started GitHub Action."

      # 2. ดึงโค้ดลงมา
      - name: Check out the repo
        uses: actions/checkout@v4

      # 3. Login เข้า Docker Hub
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build และ Push Image (ระบุ Tag latest ให้ชัดเจน 100%)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.IMAGE_NAME }}:latest
            ${{ vars.IMAGE_NAME }}:${{ github.sha }}

      # 5. ยิง Webhook ไปสะกิด VPS ให้ดึง Image ใหม่ไปรัน
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: http://14.207.142.57:9000/hooks/redeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }} # แนะนำให้ใช้ Secret จาก GitHub
          data: '{"project_group": "${{ vars.PROJECT_GROUP }}", "discord_webhook": "${{ secrets.DISCORD_WEBHOOK }}", "webhook_secret": "${{ secrets.WEBHOOK_SECRET }}"}'
          verbose: true

      # 6. แจ้งเตือนเสร็จสิ้นเข้า Discord
      - name: Discord notification (finish)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: github_server
          DISCORD_AVATAR: https://picsum.photos/id/237/200/300
        uses: Ilshidur/action-discord@master
        with:
          args: "The project {{ EVENT_PAYLOAD.repository.full_name }} has finished GitHub Action."